#!/bin/bash

# remove output file if it already exists
if [ -e ./PRresult ]; then
  rm PRresult
fi

# make new output file
touch PRresult

echo "This script runs page rank and measures user and system time."
echo "Average time results can befound in file PRresult"

graphs="kron.sg urand.sg web.sg road.sg twitter.sg"
synth="kron.sg urand.sg"

for g in $synth; do
  echo "Tests for $g" >> PRresult
  ./pr -f /lscratch/graphs/$g | grep "Average Time:" >> PRresult
  echo "" >> PRresult
done