#!/bin/bash

# remove output file if it already exists
if [ -e ./tsresult ]; then
  rm tsresult
fi

# make new output file and temp file
touch tsresult
touch timeresults

# for future reference awk -F '[ ):]*' '$0=$NF' ./tsresult

# run tests at scale 15, 18, 20, 22
for scale in 15 18 20 22
do
  2>timeresults /usr/bin/time --verbose ./converter -g $scale -s -m -b kg-s-m.sg | grep "Build" >> tsresult
  grep "Maximum resident" ./timeresults >> ./tsresult
  2>timeresults /usr/bin/time --verbose ./converter -g $scale -s -b kg-s.sg | grep "Build" >> tsresult
  grep "Maximum resident" ./timeresults >> ./tsresult
  2>timeresults /usr/bin/time --verbose ./converter -g $scale -m -b kg-m.sg | grep "Build" >> tsresult
  grep "Maximum resident" ./timeresults >> ./tsresult
  2>timeresults /usr/bin/time --verbose ./converter -g $scale -b kg.sg | grep "Build" >> tsresult
  grep "Maximum resident" ./timeresults >> ./tsresult
done

rm timeresults
